### ISSUE TITLE
Video preview

### ISSUE THREAD

**Issue by seamug** [geocine/sjremote#1]
hi
Is it at all possible to do a video preview on the app?

**Comment by geocine** [comment]
video preview is not supported in this build. you may fork the project and add that feature if you like

**Comment by seamug** [comment]
Hi Alvan

Thanks for your reply. Do you know what is the command for video preview? Im a noob. 

Thanks

Apologies for the brevity of this message

**Comment by geocine** [comment]
@seamug 

Yes access it via rtsp `rtsp://192.168.1.254/sjcam.mov`

**Comment by seamug** [comment]
Hi Alvan 

Thanks. Does this app works with both 4000 and 5000?

Apologies for the brevity of this message

**Comment by geocine** [comment]
I have only tested this on 5000 because that is the device that I have.

**Comment by nofirg** [comment]
I have a sj5000plus and video stream is available by rtsp://192.168.42.1/live

**Comment by geocine** [comment]
@nofirg Thanks that is good to know
