### ISSUE TITLE
Download recorded video or captured image

### ISSUE THREAD

**Issue by udeepak** [geocine/sjremote#2]
First of all, thanks a lot for this code! Can you also add a feature in this to show how to download a video or image from SJCam? That would be great!

**Comment by geocine** [comment]
Hi I don't have much time to work on this . But if you would like to accomplish this. If you connect to 192.168.1.254 via http you can access the file system and copy the movies/photos from the SD card.

**Comment by udeepak** [comment]
Hey. Thanks a lot! That did work out :)

**Comment by geocine** [comment]
You are welcome :)
